version: '2'

volumes:
  build:
    driver: local
  cache:
    external: true

services:
  test:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - cache:/cache
      - build:/build
    links:
      - mongodb
      - mongo-seed
    environment:
      MONGODB_HOST: mongodb
    ports:
      - "3000:3000"

  builder:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - build:/build
    working_dir: /usr/src/app
    command: ["tar", "cvfz", "/output/nodejs-app.tar.gz", "app.js", "node_modules", "models", "routes", "package.json"]

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongo-seed:
    build: 
      context: ../../
      dockerfile: db/mongo/docker/dev/Dockerfile
    links:
      - mongodb

  agent:
    image: ${DOCKER_REGISTRY}/nutanix/ansible
    links:
      - mongodb
    environment:
      PROBE_HOST: "mongodb"
      PROBE_PORT: "27017"
    command: ["probe.yml"]
